language: php

php:
  - 5.4
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: 5.5
    - php: hhvm

before_script:
  - psql -c 'CREATE DATABASE titon_test;' -U postgres
  - composer selfupdate
  - composer install

notifications:
  email: false